#:schema https://api.nuon.co/v1/general/config-schema?source=inputs
[[group]]
name         = "dns"
description  = "DNS Configrations"
display_name = "Configurations for the root domain for Route53"

[[input]]
name         = "sub_domain"
description  = "The sub domain for the penpot service"
default      = "penpot"
display_name = "Sub Domain"
group        = "dns"
